services:
  - type: web
    name: tinyurl-backend
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/tinyurl-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://demo-host:5432/demo-db
      - key: SPRING_DATASOURCE_USERNAME
        value: demo-user
      - key: SPRING_DATASOURCE_PASSWORD
        value: demo-pass
    autoDeploy: true

